"""
OVERVIEW:
This strategy uses two moving averages of different periods, short and long
(fast and slow), to indicate a trend's direction. When the fast moving average
(short) crosses above the slow moving average (long), the trend is deemed to
have become bullish and represents a potential buying opportunity.
The system seeks to exit (sell) an open position when the fast moving average
crosses below the slow moving average.

PARAMETER DESCRIPTION:
The Moving Average is the average price of a stock over a given period.
For example, to calculate a 50 day Simple Moving Average (SMA), add the last
50 closing price values and divide the sum by 50. There are other, more complex
ways to calculate a Moving Average, but the Simple Moving Average is still the
most commonly used. Typical trend values look out over 20 and 50 days although
50 and 200 days are also frequently used.

Source: https://eresearch.fidelity.com/

###############################################################################

Calculating Moving Averages based on daily alphas increases slightly the number
of signals generated on average across entities.
Average returns of winner entities and loser entities are greater in absolute
terms (0.3365 vs 0.2994 and -0.235 vs -0.1706)

"""
from itertools import groupby
import pandas as pd

from blvresearch.concat.signals.price_based.moving_average import (
    adjust_series_of_signals
)
from blvresearch.concat.signals.utils import (
    remove_consecutive_values
)
from blvutils.finance import to_prices


def get_dmac_signals(data, long_window, short_window, confirmation_window):
    prices = to_prices(data['abs_ret'], set_first_to_na=True)
    _short = pd.ewma(prices, span=short_window)
    _long = pd.ewma(prices, span=long_window)
    result = _short > _long
    result = adjust_series_of_signals(result, confirmation_window)
    return remove_consecutive_values(result)


DESCRIPTION_BUY = """
This is a BUY signal generated by Dual Moving Average Crossover strategy.\n
%s days ago the fast moving average (short window) went above the slow\n
moving average (long window). This indicates bullish trend and a potential
to buy.
The signal was generated after this relation between two moving averages
prevailed over the next %s days, which was to confirm correctness of
the signal.
"""

DESCRIPTION_SELL = """
This is a SELL signal generated by Dual Moving Average Crossover strategy.\n
%s days ago the fast moving average (short window) went below the slow\n
moving average (long window). This indicates bearish trend and a potential
to sell.
The signal was generated after this relation between two moving averages
prevailed over the next %s days, which was to confirm correctness of
the signal.
"""

DESCRIPTION_COMMON = """
The fast moving average uses %s-day window, and the slow moving average uses
%s-day window. Both moving averages are exponential ones.

For all trading strategies, tha past performance does
not guarantee future results.
"""


def get_dmac_descr(signal, confirmation_window, short_window, long_window):
    if signal == True:
        result = DESCRIPTION_BUY % (confirmation_window, confirmation_window)
    elif signal == False:
        result = DESCRIPTION_SELL % (confirmation_window, confirmation_window)
    result += DESCRIPTION_COMMON % (short_window, long_window)
    return result
