"""
OVERVIEW:
First identifies important events, i.e.
(1) relevant news need to exist
(2) alpha needs to exceed expected alpha by 1 standard deviation

    Remark: alpha moments are calculated based on previous 6 months

Next for each of these days, it checks:
(1) what was the return on that day
(2) what was the return over the next 3 days
(3) if over the previous 5 or the next 3 days a buy/sell signal - generated by
    MA strategy - occurred

"""
import datetime as dt
import pandas as pd

from blvresearch.concat.signals.utils import remove_consecutive_values
from blvresearch.concat.signals.news_based.news_common_funcs import (
    get_days_to_check
)
from blvresearch.concat.signals.price_based.moving_average import (
    adjust_series_of_signals
)


DAYS_AFTER = 3
FIRST_LOC = (20 +  # MA window
             3 +   # MA confirmation window
             5)    # days to look back for MA signal
LAST_LOC = -DAYS_AFTER


def get_signals(days_to_check, returns, first_loc, last_loc):
    first_day = returns.index[first_loc + FIRST_LOC]
    last_day = returns.index[last_loc + LAST_LOC]

    ma_signals = get_ma_signals(returns, window=20, confirmation_window=3)
    ma_signals = ma_signals.reindex(data.index)

    result = pd.Series(index=returns.index)
    for date in days_to_check[first_day:last_day].index:
        loc = returns.index.get_loc(date)
        signal_day = returns.index[loc + DAYS_AFTER]
        if ((ma_signals[loc - 5:loc + 1 + DAYS_AFTER] == False).any() and
            _is_negative_suprise(returns, date)):
            result[signal_day] = False
        elif ((ma_signals[loc - 5:loc + 1 + DAYS_AFTER] == True).any() and
              _is_positive_suprise(returns, date)):
            result[signal_day] = True
    return remove_consecutive_values(result)


def _is_negative_suprise(returns, date):
    loc = returns.index.get_loc(date)
    if (returns[date] < 0 and
        returns[loc + 1:loc + 1 + DAYS_AFTER].sum() < 0):
        return True
    return False


def _is_positive_suprise(returns, date):
    loc = returns.index.get_loc(date)
    if (returns[date] > 0 and
        returns[loc + 1:loc + 1 + DAYS_AFTER].sum() > 0):
        return True
    return False


def func(x):
    if x < 0:
        return -1
    else:
        return 1


def get_ma_signals(returns, window, confirmation_window):
    avg = pd.ewma(returns, span=window)
    result = returns > avg
    result = adjust_series_of_signals(result, confirmation_window)
    return result
